services:
  posts-db:
    image: postgres
    container_name: posts-db
    environment:
      - POSTGRES_DB=postsDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "posts-db-data:/var/lib/postgresql"
    networks:
      - linkedin-network

  user-db:
    image: postgres
    container_name: user-db
    environment:
      - POSTGRES_DB=userDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "user-db-data:/var/lib/postgresql"
    networks:
      - linkedin-network

  posts-service:
    image: debendracet123/linked-in/posts-service
    container_name: posts-service
    networks:
      - linkedin-network
    depends_on:
      - posts-db

  user-service:
    image: debendracet123/linked-in/user-service
    container_name: user-service
    networks:
      - linkedin-network
    depends_on:
      - user-db

networks:
  linkedin-network:

volumes:
  posts-db-data:
  user-db-data:
